# Site settings
title: "Azzadiva Sawungrana's Resume"
description: "Student at University of Twente"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Azzadiva Sawungrana"
resume_title: "Student at University of Twente"

# used for the contact button in _layouts/resume.html
resume_contact_email: "azzadv@outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "31 630 5975 20"
resume_contact_address: "Boulevard 1945 4 7511AE Enschede"

#resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info: "true"

resume_header_intro: "<p>Spatial Engineering student at the University of Twente with over six years of experience in the geospatial industry, specializing in GIS and location intelligence systems. I have worked with clients in sectors such as retail, finance and banking, insurance, F&B, and FMCG, providing insights through geospatial analysis to improve operational efficiency and manage risks. With a data analysis product management background, I focus on making geospatial solutions accessible and relevant to broader audiences. My experience reflects my commitment to applying technical expertise in ways that deliver practical value.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
#resume_section_skills: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
#resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/sawungrana"
  resume_twitter_url:           "http://twitter.com/sawungrana"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/sawungrana"
  # resume_instagram_url:         "insert your Instagram URL here"
  #  resume_website_url:           "https://github.com/bjornamr/resume-template/raw/gh-pages/webpage/resume.pdf"
  #resume_pdf_url: "https://github.com/sawungrana/sawungrana.github.io/docs/webpage/resume.pdf"
  resume_medium_url: "https://sawungrana.medium.com"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
