# Site settings
title: "Azzadiva Sawungrana's Resume"
description: "Lead Product Manager"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Azzadiva Sawungrana"
resume_title: "Lead Product Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email: "azzadv@outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "62 857 2915 3205"
resume_contact_address: "Dorus Rijkersplein 18, 2518 DA Den Haag, Netherlands"

#resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info: "true"

resume_header_intro: "<p>As a lead product manager with over five years of experience in the B2B SaaS industry, I specialize in GIS and location intelligence systems, with a focus on the retail, F&B, and FMCG markets. My ability to identify problems and opportunities, and transform them into solutions and features, has proven to be a valuable asset in helping my clients reduce cost, risk, and improve income through geospatial analysis. I am skilled in market identification, roadmap development, and product optimization, and am known for my strategic and driven approach to work. To learn more about my background and skills, please visit my online resume at sawungrana.github.io. In addition to my expertise in product management and map technology, I am also an avid writer and have published articles on a variety of topics, including UX and RS-GIS awareness, on my blog at sawungrana.medium.com and spatialmate.com.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
#resume_section_skills: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
#resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/sawungrana"
  resume_twitter_url:           "http://twitter.com/sawungrana"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/sawungrana"
  # resume_instagram_url:         "insert your Instagram URL here"
  #  resume_website_url:           "https://github.com/bjornamr/resume-template/raw/gh-pages/webpage/resume.pdf"
  #resume_pdf_url: "https://github.com/sawungrana/sawungrana.github.io/docs/webpage/resume.pdf"
  resume_medium_url: "https://sawungrana.medium.com"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
